# Random Forest

In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [2]:
from sklearn.metrics import classification_report, confusion_matrix, mean_squared_error, r2_score

In [3]:
# load the dataset from sns 
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
# encode the features which are categorical and object using for loop 
for col in df.columns:
    if df[col].dtype == 'object' or df[col].dtype.name == 'category':
        df[col] = pd.factorize(df[col])[0]
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    0     0     2
1       10.34  1.66    1       0    0     0     3
2       21.01  3.50    1       0    0     0     3
3       23.68  3.31    1       0    0     0     2
4       24.59  3.61    0       0    0     0     4

In [6]:
# split the data into x and y
X = df.drop('sex', axis=1)
y = df['sex']

In [7]:
# train test and split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
# create train and predict the model
model = RandomForestClassifier(n_estimators=400, criterion='entropy', random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [18]:
# Evaluate the model 
print('accuracy score: ', model.score(X_test, y_test))
print('confusion matrix: \n', confusion_matrix(y_test, y_pred))
print('classification report: \n', classification_report(y_test, y_pred))

accuracy score:  0.6326530612244898
confusion matrix:
 [[ 8 11]
 [ 7 23]]
classification report:
               precision    recall  f1-score   support

           0       0.53      0.42      0.47        19
           1       0.68      0.77      0.72        30

    accuracy                           0.63        49
   macro avg       0.60      0.59      0.59        49
weighted avg       0.62      0.63      0.62        49

In [20]:
# use random forest for regression task
from sklearn.metrics import mean_absolute_error


x = df.drop('tip', axis=1)
y = df['tip']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(n_estimators=400, criterion='squared_error', random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
# evaluate the model
print('mean squared error: ', mean_squared_error(y_test, y_pred))
print('r2 score: ', r2_score(y_test, y_pred))
print('mean absolute error: ', mean_absolute_error(y_test, y_pred))
print('root mean squared error: ', np.sqrt(mean_squared_error(y_test, y_pred)))

mean squared error:  0.9058294904591818
r2 score:  0.27531979522179617
mean absolute error:  0.7562438775510194
root mean squared error:  0.9517507501752661