# 1. Standard Scaling

In [65]:
# import libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler, RobustScaler

In [37]:
# make example data 
data = {'age': [25, 30, 35, 40, 45],
        'height': [156, 234, 234, 345, 456], 
        'weight': [60, 70, 80, 90, 100]}
# convert this data into pandas dataframe
data = pd.DataFrame(data)
data

   age  height  weight
0   25     156      60
1   30     234      70
2   35     234      80
3   40     345      90
4   45     456     100

In [56]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
scaled_data
# convert this scaled data into pandas dataframe
scaled_data = pd.DataFrame(scaled_data, columns=data.columns)
scaled_data

        age    height    weight
0 -1.414214 -1.233515 -1.414214
1 -0.707107 -0.487669 -0.707107
2  0.000000 -0.487669  0.000000
3  0.707107  0.573728  0.707107
4  1.414214  1.635125  1.414214

In [58]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
# convert this scaled data into pandas dataframe
scaled_data = pd.DataFrame(scaled_data, columns=data.columns)
scaled_data

    age  height  weight
0  0.00    0.00    0.00
1  0.25    0.26    0.25
2  0.50    0.26    0.50
3  0.75    0.63    0.75
4  1.00    1.00    1.00

In [63]:
# maxabc Scaler
scaler = MaxAbsScaler()
scaled_data = scaler.fit_transform(data)
# convert this scaled data into pandas dataframe
scaled_data = pd.DataFrame(scaled_data, columns=data.columns)
scaled_data

        age    height  weight
0  0.555556  0.342105     0.6
1  0.666667  0.513158     0.7
2  0.777778  0.513158     0.8
3  0.888889  0.756579     0.9
4  1.000000  1.000000     1.0

In [66]:
# robust scaler
scaler = RobustScaler()
scaled_data = scaler.fit_transform(data)
# convert this scaled data into pandas dataframe
scaled_data = pd.DataFrame(scaled_data, columns=data.columns)
scaled_data

   age    height  weight
0 -1.0 -0.702703    -1.0
1 -0.5  0.000000    -0.5
2  0.0  0.000000     0.0
3  0.5  1.000000     0.5
4  1.0  2.000000     1.0